---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ezreal.
--- DateTime: 2023/1/8 23:09
---
--- 锁已存在
if (redis.call('exists', KEYS[2]) == 1) then
    return -997;
end
--- 设置锁
redis.call('set', KEYS[2], 1);
local stockNumber = tonumber(ARGV[1]);
redis.call('set', KEYS[1], stockNumber);

--- 释放锁
redis.call('del', KEYS[2]);
return 1