---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ezreal.
--- DateTime: 2023/1/19 11:29

--- 对应的库存键不存在
if (redis.call('exists', KEYS[1]) == 0) then
    return -996
end
--- 分桶禁用锁
if (redis.call('exists', KEYS[2]) == 1) then
    return -998
end
--- 库存调度锁
if (redis.call('exists', KEYS[3]) == 1) then
    return -997
end
if (redis.call('exists', KEYS[1]) == 1) then
    local stocksAmount = tonumber(redis.call('get', KEYS[1]))
    local quantity = tonumber(ARGV[1])
    --- 库存不够
    if (stocksAmount < quantity) then
        return -1
    end

    if (stocksAmount >= quantity) then
        redis.call('incrby', KEYS[1], 0 - quantity)
        return 1
    end
end

return -10000
