---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Ezreal.
--- DateTime: 2023/1/19 10:41
---
--- 调度
if (redis.call('exists', KEYS[2]) == 1) then
    return -998
end
--- 桶被禁用
if (redis.call('exists', KEYS[3]) == 1) then
    return -997
end
redis.call('set', KEYS[3] , 1)
local stocksAmount = tonumber(ARGV[1])
local bucketsQuantity = tonumber(ARGV[2])

redis.call('set', KEYS[1] , stocksAmount)
redis.call('set', KEYS[4] , bucketsQuantity)
redis.call('del', KEYS[3])
return 1