server:
  port: 8082
  servlet:
    context-path: /api
spring:
  servlet:
    multipart:
      max-file-size: -1 # 上传文件的值 -1为不受限制
      max-request-size: -1
  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher
#  application:
#    name: seckill-good
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: ezreal
    url: jdbc:mysql://localhost:3306/seckill?useSSL=false&characterEncoding=utf-8&serverTimezone=Hongkong
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 43.139.44.154:8848 # 注册中心的地址
#      config:
#        file-extension: yml # 文件后缀名
#    sentinel:
#      eager: true
#      transport:
#        dashboard: localhost:9999
#        port: 8719
  redis:
    host: localhost
    port: 6379
    password: ezreal

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)